---
title: "HW 2 Leaflet"
author: "Ahmed Sanda"
date: "10/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(rgdal)
library(leaflet)
library(leaflet.extras)
library(dplyr)
library(readxl)
library(stringr)
```

## Load Philadelphia map datasets into R
```{r}
bikes <- readOGR("Bike_Network.geojson")
#plot(bikes)

facilities <- readOGR("City_Facilities_pub.geojson")
#plot(facilities)

rec <- readOGR("ppr_districts_2018.geojson")
#plot(rec)
```

#Consolidated Bike map with basemap selection option and layer control for different philadelphia demographics
```{r}

# Create color palette for layer legends
bikepalette <- colorFactor(palette() , levels = levels(bikes$TYPE))
districtspalette <- colorFactor(palette(), levels = levels(rec$label))

# Render combination layered map of Philadelphia
leaflet() %>%
  # Add first base map
  addProviderTiles(providers$Stamen.Toner, group = 'Stamen')%>%
  # Add second base map
  addProviderTiles(providers$Stamen.Terrain, group = 'Terrain') %>%
  # Add layer control to select basemap and accompanying layers
  addLayersControl(baseGroups = c("Stamen", "Terrain") 
                   ,overlayGroups = c("Bike Lanes", "Districts", "Facilities")
                   ,options = layersControlOptions(collapsed = FALSE)) %>%
  # Add line data from bike lanes dataset for philly
  addPolylines(data = bikes,color = ~bikepalette(TYPE), group = "Bike Lanes") %>%
  # Add philly district polygons
  addPolygons(data = rec, color = ~districtspalette(x = label), group =  "Districts") %>%
  # Add philly public facilites markers
  addMarkers(clusterOptions = markerClusterOptions(), data = facilities, group = "Facilities", label = facilities$ASSET_NAME) %>%
  # Add bike lane type legend and only  apply when bike group is selected
  addLegend(position = "topright" , pal = bikepalette, values = bikes$TYPE, title = "Lane Type", group = "Bike Lanes") %>%
  # Add Philly districts legend and only apply for the district group selection
  addLegend(position = "topleft" , pal = districtspalette, values = rec$label, title = "Districts", group = "Districts")
  

```




